# Generated by Django 5.2.4 on 2025-07-19 02:34
from django.utils import timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apikey'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return

        superuser = User.objects.create_superuser(
            username="init_username",
            email="init@init.com",
            password="init_password",
            last_login=timezone.now()
        ) 
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser)
    ]